# Generated by Django 5.1.6 on 2025-02-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamleader',
            field=models.CharField(max_length=20),
        ),
    ]
