# Generated by Django 5.1.6 on 2025-02-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='support/'),
        ),
    ]
