# Generated by Django 5.1.6 on 2025-02-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_team_teamleader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='teamleader',
            new_name='leader',
        ),
    ]
