# Generated by Django 5.1.6 on 2025-02-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
