# Generated by Django 5.1.6 on 2025-02-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_support_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_time', models.PositiveIntegerField(help_text='Break time in minutes')),
                ('task_description', models.TextField()),
            ],
        ),
    ]
