# Generated by Django 5.1.6 on 2025-02-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_team_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
